resources:
  limits:
    cpus: 2
    memory: 4096

TZ: Europe/Berlin

bombvault:
  app_key: "3f9c1d47a8b20e65fd913c07ab4e28d5106f7be3c9a4520d8e17fb6390c2a4d1"
  http_only: true
  additional_envs:
    - name: LIBVIRT_URI
      value: qemu+ssh://root@192.0.2.10/system?socket=/run/truenas_libvirt/libvirt-sock

network:
  host_network: true
  web_port:
    bind_mode: published
    port_number: 38081

ix_volumes:
  config: /opt/tests/mnt/bombvault/config

storage:
  config:
    type: ix_volume
    ix_volume_config:
      dataset_name: config
      create_host_path: true
  host_data:
    type: host_path
    host_path_config:
      path: /opt/tests/mnt/bombvault/hostdata
      create_host_path: true
  additional_storage:
    - type: host_path
      read_only: true
      mount_path: /extra
      host_path_config:
        path: /opt/tests/mnt/bombvault/extra
        create_host_path: true

labels: []
